### ISSUE TITLE
Deployed apps are failing

### ISSUE THREAD

**Issue by Romes8** [Eagles-DevOps/MiniTwit#106]
When we deploy app into droplet after some amount of time if crashes. 

I think its because the simulation is making requests. At some point there is an error which I guess makes the app fail.

**Comment by danielgron** [comment]
Can someone try to start it and direct Std output to a text file? Ie ./Minitwit > log txt
?

I can't remember what the app is called on the server but something to that effect...

**Comment by danielgron** [comment]
I'm not on my laptop for another few hours, so if someone else is able to try that would be great.

**Comment by Hopeberg** [comment]
Good suggestion. I have tested with two other droplets I created, and as soon as I close my browser down, the droplets were destroyed.. seems like they are not as persistent as we want them to be

**Comment by Hopeberg** [comment]
I tested by creating two droplets, and as soon as I close the console they run in, the app can no longer be accessed.

**Comment by rasmus-bn** [comment]
I think if we add "&" after the run command that should start the app as a new process (different from the process running from ssh connection). Will try this

**Comment by danielgron** [comment]
Oh Yeah if it is running straight in the ssh that's a problem. Are you sure we want ampersand and not nohup?

**Comment by rasmus-bn** [comment]
> cool, let us know how it goes

I am not completely sure how to reproduce this issue as I don't the steps that you took. 

> Oh Yeah if it is running straight in the ssh that's a problem. Are you sure we want ampersand and not nohup?

Yeah that is propably better. ([reference](https://stackoverflow.com/questions/15595374/whats-the-difference-between-nohup-and-ampersand))

**Comment by Hopeberg** [comment]
Try to reproduce the steps. I don't think our server is persistent in any way.... Not from what I have tested. 
The consoles were running last night, and when I woke up today, the apps are down again.

**Comment by Hopeberg** [comment]
In addition, the API failed this morning with the following error : "all authentication methods failed", despite being up and running yesterday. So I have decided to run two new droplets now...

**Comment by Hopeberg** [comment]
For the API console, after cloning the repo, switch to branch dploy to run the minitwit-api.go. 
I fixed an error in the format of a go version in a mod file on this branch. Otherwise it will not run the file.

**Comment by Hopeberg** [comment]
Thanks for the tips, tried running these commands on the consoles and it worked: 

go run minitwit.go &
go run minitwit-api.go &

However, the main app does not load completely for some reason. 
<img width="714" alt="Skærmbillede 2024-02-28 kl  09 53 57" src="https://github.com/Eagles-DevOps/MiniTwit/assets/158263197/f28d49f8-247c-4e47-b5db-940cc019c181">

**Comment by Hopeberg** [comment]
When I come back from a meeting, I'll spin up our team droplets and make them a background job. Hopefully will solve the issue

**Comment by Hopeberg** [comment]
I tested some more.. current status: 

Main app works as a background job, but it does not load the page correctly. 
<img width="712" alt="Skærmbillede 2024-02-28 kl  13 50 11" src="https://github.com/Eagles-DevOps/MiniTwit/assets/158263197/a886ac79-26dd-4ec3-85ce-1e316ffb8f01">

Api does not work as a background job, as soon as I close the api droplet console, the process ends, and the api is no longer accessible.

**Comment by Hopeberg** [comment]
the background jobs are working, and I can now close the console and app are still accessible. 
Hoever, main app does not load correct - not sure why? 
<img width="712" alt="Skærmbillede 2024-02-28 kl  14 25 23" src="https://github.com/Eagles-DevOps/MiniTwit/assets/158263197/30b1846e-9004-4ac4-965b-bfe4e17d6494">

**Comment by Romes8** [comment]
@Hopeberg would it be possible to merge your `dploy` branch into `CI/CD-Pipeline` so we are know where are the related changes to this issue.

**Comment by Romes8** [comment]
> the background jobs are working, and I can now close the console and app are still accessible. Hoever, main app does not load correct - not sure why? <img alt="Skærmbillede 2024-02-28 kl 14 25 23" width="712" src="https://private-user-images.githubusercontent.com/158263197/308563909-30b1846e-9004-4ac4-965b-bfe4e17d6494.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMzM2ODksIm5iZiI6MTcwOTEzMzM4OSwicGF0aCI6Ii8xNTgyNjMxOTcvMzA4NTYzOTA5LTMwYjE4NDZlLTkwMDQtNGFjNC05NjViLWJmZTRlMTdkNjQ5NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyOFQxNTE2MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNGUxZWI3NWExYzE4NTgzYWY1OTMyMDdmNzkwZDQzNTdlNGJhMTcyYjhiNThlNThlNTFmYzE5MGMxYTczNmIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RYQrgFgDI6SvQjoYsLL_bhRgJIqkK3St0zGU8JFd938">

Images are visible for me on the sire. Can somebody check and see how it is for them ? @everyone

**Comment by Hopeberg** [comment]
Issue is fixed with commands for background jobs making the apps persistent
