### ISSUE TITLE
use reserved IP for droplet

### ISSUE THREAD

**Issue by janlishak** [Eagles-DevOps/MiniTwit#112]

**Comment by janlishak** [comment]
check #83 for information

**Comment by danielgron** [comment]
I agree with using static/reserved ip.
I also just realized we could benefit from setting up dns regardless, even if not for use as improvised load balancer.
We are a lot more flexible with how we implement the servers and networking if we have a dns set up for the simulator.
Then we are not relying on a PR to go through with an updated IP in the devops repo.
