### ISSUE TITLE
cron job - make backups for the db

### ISSUE THREAD

**Issue by janlishak** [Eagles-DevOps/MiniTwit#165]
options (I know of):
- droplet cron job ( downside will have to recreat droplet to apply settings)
- make cron container ( good middle ground, maybe too complex)
- add a job to our go code (we'll have to program it) but maybe the best because I'll be easy to use digital ocean spaces (buckets) 

issue is related to #145 if we use digital ocean for saving the backups

**Comment by danielgron** [comment]
Doing it in the existing go code will probably introduce a problem if (when) we need to scale. Then we'll do a copy per instance.

**Comment by Hopeberg** [comment]
good reflections :) I am working on branch cron and added cron job to our go code. For now, I created a backups folder in our repo. I made a PR in case we decide to go with this backup solution for now. 

I agree with both Jan and Daniel. I also believe recreation of droplet is a no-go. If we run into scaling problems, we could improve the backup solution in a while :)
