### ISSUE TITLE
Move to new DB engine

### ISSUE THREAD

**Issue by rasmus-bn** [Eagles-DevOps/MiniTwit#176]
We should decide on:
* DB engine (Postgress vs Mysql e.g.)
* VM or managed DB?
* How to minimize down time during migration
* How do we manage DB secrets?

Suggested solution:
1. Take snapshot of the SQLite DB
2. Publish Snapshot to new DB
3. Point application to new DB

As Helge advised us. First we should implement monitoring before moving database. 

#177 #179 need to be resolved before

**Comment by rasmus-bn** [comment]
We decided on using a managed DB service.

Postgress vs MySQL is still an open question

**Comment by danielgron** [comment]
I would argue that there are subtasks that are not blocked:

Infrastructure as code for create the DB.
  - Isolated from other environment creation as it should be persisted even if we recreate our environment.
  
Create postgresDbFacade.go
  - Implement identical methods to the existing
 
 Update tests to run on postgres instance
   - up for debate - but might be useful to be sure we don't introduce errors

**Comment by rasmus-bn** [comment]
This might be overkill but in order to isolate the DB from the public network it could be a option to put in a virtual network (VPC) together with the VM and then only expose the VM to the internet.

https://docs.digitalocean.com/products/networking/vpc/concepts/best-practices/

Downsides of this:
* Increased complexity
* Can't easily connect to the DB from local developer PC

**Comment by Romes8** [comment]
Closing since we have a new DB up and running
