### ISSUE TITLE
Setup prometheus

### ISSUE THREAD

**Issue by rasmus-bn** [Eagles-DevOps/MiniTwit#177]
* Consider if Prometheus is the right tool? (log reflections)
* Configure the docker container
* Configure the application
* Identify what we want to log
    * consider whether it should be before or after DB updates in the code
    * Consider what metrics could be relevant while doing the DB migration
* Instrument application to use Prometheus
* Consider how persistence should work?

**Comment by Hopeberg** [comment]
We have setup 3 metrics (cpuGauge, responseCounter and requestDuration) and registered with Prometheus in minitwit-api.go.

**Comment by Hopeberg** [comment]
Status: 
Middleware is set up with two metrics: responseCounter and requestDuration
Both metrics show up under /metrics

**Comment by Hopeberg** [comment]
Our metrics do not show up under prometheus at localhost:9090. 
I corrected an error in our prometheus.yml: 
correction from: 
- targets: ['minitwit-api:15001']
to: 
- targets: ['api:15001']

It did not solve the error with metrics not showing up in prometheus
