### ISSUE TITLE
Add Logging

### ISSUE THREAD

**Issue by Romes8** [Eagles-DevOps/MiniTwit#187]
We have implemented Loki with Promtail. 

To see what is happening in our application we can add logs. (print statements)
These will get picked up by Promtail and processed with Loki. We can visualize them in Grafana afterward. 

Potential way how to add print statements: 
Since we can look for print statements in Grafana that have a specific string we can format our logs to be more descriptive. 
Example for a new error log: 	
`fmt.Println("ERROR: User not found in the database")`

This way we can query for all the logs that have "ERROR" and get all the error messages our application emits. 

Same idea can be used for successful operation such as: 

`fmt.Println("SUCCESS: New user registered.")`

**Comment by rasmus-bn** [comment]
Consider using a logging library

**Comment by Romes8** [comment]
mt.Fprintf(os.Stderr, "number of foo: %d", nFoo)

**Comment by Romes8** [comment]
Made some initial commits:

The library used for logging - "go.uber.org/zap"
Since we need to save logs - I am writing the logs into a file in "terraform\ephemeral\logs\logs.log" and mounting this  file to the API container. 

What am I struggling with is to make Loki read this file and logs inside. 


usage example: 
Set up: 
`//logger set up  
	config := zap.NewProductionConfig()
	config.OutputPaths = []string{"./logs/logs.log"}
	logger, err := config.Build()
	if err != nil {
		log.Fatal(err)
	}
	lg := logger.Sugar()`

in code: 
`		lg.Info("Using postgress as main DB.")
`

Logs can have different type based on the weight. - Error, Info, Fatal, Warning, ...

**Comment by danielgron** [comment]
It looks a little weird to me to have it mounted at "terraform\ephemeral\logs\logs.log", is that just while testing?

Do I understand it correctly that you have it set up and done some configuration for loki pointing at a path where you expect a logfile, but nothing shows up?
Is there an error saying it can't find file at path, or any other indication?

**Comment by danielgron** [comment]
Are your latest commits pushed?
The latest update to origin/logging seems to be a few days old.

**Comment by Romes8** [comment]
> It looks a little weird to me to have it mounted at "terraform\ephemeral\logs\logs.log", is that just while testing?
> 
> Do I understand it correctly that you have it set up and done some configuration for loki pointing at a path where you expect a logfile, but nothing shows up? Is there an error saying it can't find file at path, or any other indication?

Having it in the terraform has no real reason. We can have this anywhere we want but since we have sqlite-adb also located there that was my first pick. 

Pushed the changes now

**Comment by danielgron** [comment]
After looking at it for a bit:

Running the ephemeral docker compose locally gives the error:
2024/03/17 21:35:51 open sink "./logs/logs.log": open ./logs/logs.log: is a directory

Fix by changing volume in api:
./logs/:/usr/src/app/logs/

Promtail directory is set for the path used in the volume for api rather than the one used in promtail.
change in promtail.yaml:
__path__: /var/log/api/logs.log

These changes leads to:

![image](https://github.com/Eagles-DevOps/MiniTwit/assets/16220541/38f9451c-ff37-4d97-840a-6d2607cbd04b)

Still a bit of work left as it keeps pushing the same log lines, but it's a start.

**Comment by Romes8** [comment]
Added logs into minitwit-api. 

 Introduced logger which is located in minitwit/logger/logger.go
 The reason for this was the importing issue I was facing. If we initialize logger f.ex. in minitwit-api.go we would need to import this function into another file. However, this would create circular dependency logic which GO is not happy with. 
 
 With this system, we can import it into any file. 
 
 **Usage of logger:** 
 
 1. import -  `"minitwit-api/logger"`
 2. Initialize the logger - `var lg = logger.InitializeLogger()`   -- this needs to be done once within the package/folder. After we can access the logger by `lg.`
 3. log something - `	lg.Info("Listening on port 15001...")`
 
 Types of logs for now is only `lg.Info` and  `lg.Error`.
