### ISSUE TITLE
Add Grafana URL to teachers repo 

### ISSUE THREAD

**Issue by Romes8** [Eagles-DevOps/MiniTwit#192]
Make a PR to teachers repo with Grafana URL. Send login data into the teams' channel.

**Comment by Romes8** [comment]
We can make our dashboard public which will generate us a link - http://188.166.201.66:3000/public-dashboards/a4edbbfac4b544f8bf5abdc58447f4bd?orgId=1 it will also get updated once we change something. However we cannot delete this dashboard otherwise we need to create a new link and a new PR to his repo.
This way we dont need to provide him with any login info

**Comment by Slightsmiles** [comment]
What would be cases where we would delete the dashboard outside of maybe doing it when the simulation is reset?

**Comment by Romes8** [comment]
We can manipulate all the data in that dashboard we just cant delete the dashboard itself

**Comment by Romes8** [comment]
PR made - https://github.com/itu-devops/lecture_notes/pull/481
