### ISSUE TITLE
suggestion: move docs to github wiki

### ISSUE THREAD

**Issue by janlishak** [Eagles-DevOps/MiniTwit#193]
Github provides a way to store markdown docs as wiki. 
It's easily accessible (wiki tab) and there is no need to commit and merge anything.

**Comment by Romes8** [comment]
Nice catch. I did not know about this option. We can have a look at it. 

If we go with this approach then #191 this becomes outdated

**Comment by Romes8** [comment]
Moved all the current docs to Wiki section. No need to edit the ones we have in the repo. 

I would suggest deleting them since they are not needed to be in the repository next to the code.
