### ISSUE TITLE
Save logging to volume

### ISSUE THREAD

**Issue by Slightsmiles** [Eagles-DevOps/MiniTwit#197]
#187 
Currently our logs are destroyed when we destroy the container. We want them to persist for x amount of time

**Comment by danielgron** [comment]
@Slightsmiles 
@janlishak 

As per Jan's comment on Discord I think this can just be closed?

"actually the whole reason I implemented the whole loki promtail stack was to have persistent logs. (edited)
[11:57 PM]
promtial reads the logs (I think every 5 seconds) and inserts them to loki which is basically a database (edited)
[11:57 PM]
loki is persistent - docker volume"
