### ISSUE TITLE
Week 7 - Software Maintenance II

### ISSUE THREAD

**Issue by Ghmeding** [Eagles-DevOps/MiniTwit#201]
Hi Eagles,

Here is our test-results:

**Do you see a public timeline?:**

→ YES

**Does the public timeline show messages that the application received from the simulator?** 

→ No, the messages are old and not the ones from the simulator

**Can you create a new user?**

→ Yes

**Can you login as a new user?**

→ Yes

**Can you write a message?**

→ Yes

**After publishing a message, does it appear on your private timeline?**

→ Yes

**Can you follow another user?**

→ No, the profiles of the other users are not accessible (no links or redirecting)

**Comment by Slightsmiles** [comment]
Fixed

**Comment by janlishak** [comment]
As far as I see this is fixed, closing the issue.

**Comment by Slightsmiles** [comment]
It's fixed when the pending pull request is merged
