### ISSUE TITLE
Setting up GitHub action to deploy to digital ocean

### ISSUE THREAD

**Issue by rasmus-bn** [Eagles-DevOps/MiniTwit#42]
Prerequisite:
- Working vagrant file for deploying the #41 

Steps
1. Setup Github -> Digital Ocean authentication
2. Update the vagrant setup to target Digital ocean

Depends on #41

**Comment by Romes8** [comment]
Waiting to get approved as student to be able to read free credits to Digital Ocean

**Comment by Romes8** [comment]
Created an action file that runs a vagrant file. 

Having some issues setting up correctly and making vagrant file run.

**Comment by Romes8** [comment]
Not sure how can we automate the vagrant file and store the secrets as well

**Comment by danielgron** [comment]
If you write a bit about the error you get I can try to look at it

**Comment by Romes8** [comment]
Tied up with #96
