### ISSUE TITLE
Move all db-related code to dbfacade.go

### ISSUE THREAD

**Issue by danielgron** [Eagles-DevOps/MiniTwit#74]
There are db queries in the api's now. All db-specific code should live in the db-facade

**Comment by Hopeberg** [comment]
All API's use db queries, and it does not make sense to move all api's to dbfacade

**Comment by danielgron** [comment]
The apis themselves should stay where they are, but ideally we would try to have the api methods behave like Messages api method does now where everything related to handling reading from the request and writing the response is handled by the api and any code specific to the sqlite ie db connections sqlite specific queries etc should be living separately. It is not high priority now, but it seems likely it will be nice to have if we want more flexibility with the db implementation

**Comment by Slightsmiles** [comment]
I kept the queries in the api layer to have our post be a single method in db-facade. i can split them into multiple methods remove all queries from the api @danielgron ?
